name = "dwicuy123"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "35.219.50.99:443"
UUID = "bebee030-7449-4939-b04b-3bb97e4a8361"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
